### ISSUE TITLE
Disconnecting slots

### ISSUE THREAD

**Issue by msteinbeck** [retuxx/sig4j#1]
I need to figure out if it is possible to disconnect arbitrary slots. At least a `clear` method should be  provided

**Comment by pmouraguedes** [comment]
Tried with Groovy closures as slots and was able to disconnect a specific slot. 
I'm glad to share the code if you have interest.

Great library!

**Comment by msteinbeck** [comment]
> Great library!

Thank you very much :).

> Tried with Groovy closures as slots and was able to disconnect a specific slot.

This library has been designed for being a Java only library without dependencies making Groovy no option for me.
